# docker-compose.yml
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ELawScrapper
    ports:
      - "1433:1433"
